[package]
name = "uwl"
version = "0.2.4"
authors = ["Alex M. M. <acdenissk69@gmail.com>"]
description = "Unicode-aware stream of characters"
repository = "https://github.com/acdenisSK/uwl"
license = "MIT"

[dependencies]
