[package]
name = "uwl"
version = "0.6.0"
authors = ["Alex M. M. <acdenissk69@gmail.com>"]
description = "A management stream for bytes and characters"
repository = "https://github.com/acdenisSK/uwl"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
